// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for different platforms
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase config values
  // The proper way to generate this file is to use the FlutterFire CLI:
  // https://firebase.google.com/docs/flutter/setup
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9T8jaLZbV943CP6PANLzYi8Mwy6QozGw',
    appId: '1:908754380268:android:1509b0a522da527df40cc9',
    messagingSenderId: '908754380268',
    projectId: 'pocketpayout-bb825',
    authDomain: 'pocketpayout-bb825.firebaseapp.com',
    storageBucket: 'pocketpayout-bb825.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9T8jaLZbV943CP6PANLzYi8Mwy6QozGw',
    appId: '1:908754380268:android:1509b0a522da527df40cc9',
    messagingSenderId: '908754380268',
    projectId: 'pocketpayout-bb825',
    storageBucket: 'pocketpayout-bb825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9T8jaLZbV943CP6PANLzYi8Mwy6QozGw',
    appId: '1:908754380268:android:1509b0a522da527df40cc9',
    messagingSenderId: '908754380268',
    projectId: 'pocketpayout-bb825',
    storageBucket: 'pocketpayout-bb825.firebasestorage.app',
    iosClientId: '908754380268-app-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocket_payout_bd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9T8jaLZbV943CP6PANLzYi8Mwy6QozGw',
    appId: '1:908754380268:android:1509b0a522da527df40cc9',
    messagingSenderId: '908754380268',
    projectId: 'pocketpayout-bb825',
    storageBucket: 'pocketpayout-bb825.firebasestorage.app',
    iosClientId: '908754380268-app-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocket_payout_bd',
  );
} 